---
title: "P8105_hw3_qh2251"
author: "Paulina Han"
date: "2021/10/14"
output: github_document
---
```{r}
library(tidyverse)
library(p8105.datasets)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

# Problem 1

```{r}
#load the data
data("instacart")

# summary the aisles
 aisels_df1 = 
   instacart %>% 
  group_by(aisle) %>% 
  summarize(num = n()) %>% 
   arrange(desc(num))

# plotting the aisles and their sales
 aisels_df2 =   
  instacart %>% 
  group_by(aisle) %>% 
  summarize(num = n()) %>% 
    filter(num > 10000) %>% 
    arrange(desc(num))
    
 aisels_df2 %>% 
 ggplot(aes(x = aisle, y = num)) + 
  geom_point() + 
  labs(
    title = "Aisle Sale",
    x = "aisles",
    y = "number of item",
    ) +
    geom_text(label = pull(aisels_df2, aisle), nudge_x = 0.25, nudge_y = 0.25, check_overlap = T)+
   theme(axis.text.x=element_blank())
    
# most popular product in each aisle
 aisels_df3 = 
   instacart %>% 
   filter(aisle %in% c("baking ingredients","dog food care","packaged vegetables fruits")) %>% 
   group_by(aisle, product_name) %>% 
   summarise(product_num = n()) %>% 
   arrange(desc(product_num),.by_group = T) %>% 
   slice_max(order_by = product_num,n = 3)  

#make a table
   aisels_df3 %>% 
    knitr::kable()
 
# mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week
hour_df = 
  instacart %>% 
  filter(product_name %in% c("Pink Lady Apples","Coffee Ice Cream"))%>% 
  group_by(product_name,order_dow) %>% 
  summarize(mean_order_time = round(mean(order_hour_of_day),2)) %>% 
  pivot_wider(
    names_from = order_dow,
    values_from = mean_order_time
  ) 

#rename the colunms
colnames(hour_df) = c("product_name","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday")
 
#print table
hour_df %>% 
  knitr::kable()
  
```
There are 134 aisles and the fresh vegetables aisle is the where most items are ordered from.

